# Site settings
title: PlantCV
baseurl: ''
# url: http://nfahlgren.github.io/plantcv

# Build settings
markdown: redcarpet
highlighter: pygments

# Jekyll-Bootstrap
JB:
    version: 2.0.3
    BASE_PATH : http://nfahlgren.github.io/plantcv
